<?php
return array (
  27 => 
  array (
    'posid' => '27',
    'modelid' => '0',
    'catid' => '26',
    'name' => '合作伙伴',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  38 => 
  array (
    'posid' => '38',
    'modelid' => '0',
    'catid' => '33',
    'name' => '责任与关怀',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  45 => 
  array (
    'posid' => '45',
    'modelid' => '0',
    'catid' => '40',
    'name' => '关于我们滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  41 => 
  array (
    'posid' => '41',
    'modelid' => '0',
    'catid' => '30',
    'name' => '工会工作特别推荐（手机）',
    'maxnum' => '1',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  42 => 
  array (
    'posid' => '42',
    'modelid' => '0',
    'catid' => '31',
    'name' => '员工生活(手机)',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  43 => 
  array (
    'posid' => '43',
    'modelid' => '0',
    'catid' => '32',
    'name' => '健康安全环境(手机)',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  46 => 
  array (
    'posid' => '46',
    'modelid' => '0',
    'catid' => '41',
    'name' => '新闻动态滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  47 => 
  array (
    'posid' => '47',
    'modelid' => '0',
    'catid' => '42',
    'name' => '产品中心滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  48 => 
  array (
    'posid' => '48',
    'modelid' => '0',
    'catid' => '43',
    'name' => '科技创新滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  49 => 
  array (
    'posid' => '49',
    'modelid' => '0',
    'catid' => '44',
    'name' => '党群园地滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  50 => 
  array (
    'posid' => '50',
    'modelid' => '0',
    'catid' => '45',
    'name' => '社会责任滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  51 => 
  array (
    'posid' => '51',
    'modelid' => '0',
    'catid' => '46',
    'name' => '人力资源滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  52 => 
  array (
    'posid' => '52',
    'modelid' => '0',
    'catid' => '22',
    'name' => '视频推荐',
    'maxnum' => '1000',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  53 => 
  array (
    'posid' => '53',
    'modelid' => '0',
    'catid' => '47',
    'name' => '检验检测',
    'maxnum' => '3',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  54 => 
  array (
    'posid' => '54',
    'modelid' => '0',
    'catid' => '48',
    'name' => '汽车领域',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  55 => 
  array (
    'posid' => '55',
    'modelid' => '0',
    'catid' => '49',
    'name' => '轨道交通',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  37 => 
  array (
    'posid' => '37',
    'modelid' => '0',
    'catid' => '32',
    'name' => '健康安全环境特别推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  36 => 
  array (
    'posid' => '36',
    'modelid' => '0',
    'catid' => '32',
    'name' => '健康安全环境',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  35 => 
  array (
    'posid' => '35',
    'modelid' => '0',
    'catid' => '31',
    'name' => '员工生活',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  28 => 
  array (
    'posid' => '28',
    'modelid' => '0',
    'catid' => '11',
    'name' => '推荐产品',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  25 => 
  array (
    'posid' => '25',
    'modelid' => '0',
    'catid' => '20',
    'name' => '行业动态',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  44 => 
  array (
    'posid' => '44',
    'modelid' => '0',
    'catid' => '39',
    'name' => '首页滚动图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  19 => 
  array (
    'posid' => '19',
    'modelid' => '0',
    'catid' => '17',
    'name' => '友情链接',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  20 => 
  array (
    'posid' => '20',
    'modelid' => '0',
    'catid' => '10',
    'name' => '首页新闻特别推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  21 => 
  array (
    'posid' => '21',
    'modelid' => '0',
    'catid' => '10',
    'name' => '首页新闻推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  22 => 
  array (
    'posid' => '22',
    'modelid' => '0',
    'catid' => '18',
    'name' => '资质荣誉',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  23 => 
  array (
    'posid' => '23',
    'modelid' => '0',
    'catid' => '19',
    'name' => '公司动态特别推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  24 => 
  array (
    'posid' => '24',
    'modelid' => '0',
    'catid' => '19',
    'name' => '公司动态推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  29 => 
  array (
    'posid' => '29',
    'modelid' => '0',
    'catid' => '28',
    'name' => '体系认证大图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  30 => 
  array (
    'posid' => '30',
    'modelid' => '0',
    'catid' => '28',
    'name' => '体系认证小图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  31 => 
  array (
    'posid' => '31',
    'modelid' => '0',
    'catid' => '29',
    'name' => '党建特别推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  32 => 
  array (
    'posid' => '32',
    'modelid' => '0',
    'catid' => '29',
    'name' => '党建推荐',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  33 => 
  array (
    'posid' => '33',
    'modelid' => '0',
    'catid' => '29',
    'name' => '党建轮播图',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  34 => 
  array (
    'posid' => '34',
    'modelid' => '0',
    'catid' => '30',
    'name' => '工会工作',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
  56 => 
  array (
    'posid' => '56',
    'modelid' => '0',
    'catid' => '50',
    'name' => '新航海',
    'maxnum' => '20',
    'extention' => '',
    'listorder' => '0',
    'siteid' => '0',
    'thumb' => '',
  ),
);
?>